-- Create default units for LSPU KMIS
INSERT INTO units (id, code, name, "createdAt", "updatedAt") VALUES
  (gen_random_uuid(), 'CAS', 'College of Arts and Sciences', NOW(), NOW()),
  (gen_random_uuid(), 'CBAA', 'College of Business Administration and Accountancy', NOW(), NOW()),
  (gen_random_uuid(), 'CCS', 'College of Computer Studies', NOW(), NOW()),
  (gen_random_uuid(), 'CCJE', 'College of Criminal Justice Education', NOW(), NOW()),
  (gen_random_uuid(), 'COE', 'College of Engineering', NOW(), NOW()),
  (gen_random_uuid(), 'CIT', 'College of Industrial Technology', NOW(), NOW()),
  (gen_random_uuid(), 'CIHTM', 'College of International Hospitality and Tourism Management', NOW(), NOW()),
  (gen_random_uuid(), 'CLAW', 'College of Law', NOW(), NOW()),
  (gen_random_uuid(), 'CONAH', 'College of Nursing and Allied Health', NOW(), NOW()),
  (gen_random_uuid(), 'CTE', 'College of Teacher Education', NOW(), NOW()),
  (gen_random_uuid(), 'SMU', 'Supply and Management Unit', NOW(), NOW()),
  (gen_random_uuid(), 'SMO', 'Security Management Office', NOW(), NOW()),
  (gen_random_uuid(), 'SFA', 'Scholarship and Financial Assistance', NOW(), NOW()),
  (gen_random_uuid(), 'RMO', 'Records Management Office', NOW(), NOW()),
  (gen_random_uuid(), 'RDS', 'Research and Development Services', NOW(), NOW()),
  (gen_random_uuid(), 'OSAS', 'Office of the Student Affairs and Services', NOW(), NOW()),
  (gen_random_uuid(), 'REG', 'Office of the Registrar', NOW(), NOW()),
  (gen_random_uuid(), 'MIS', 'Management Information Systems', NOW(), NOW()),
  (gen_random_uuid(), 'MC', 'Medical Clinic', NOW(), NOW()),
  (gen_random_uuid(), 'PU', 'Procurement Unit', NOW(), NOW()),
  (gen_random_uuid(), 'LSU', 'Legal Services Unit', NOW(), NOW()),
  (gen_random_uuid(), 'IA', 'International Affairs', NOW(), NOW()),
  (gen_random_uuid(), 'IAU', 'Internal Audit Unit', NOW(), NOW()),
  (gen_random_uuid(), 'HRMO', 'Human Resource Management Office', NOW(), NOW()),
  (gen_random_uuid(), 'GSU', 'General Services Unit', NOW(), NOW()),
  (gen_random_uuid(), 'GAD', 'Gender and Development', NOW(), NOW()),
  (gen_random_uuid(), 'CU', 'Cashier Unit', NOW(), NOW()),
  (gen_random_uuid(), 'BO', 'Budget Office', NOW(), NOW()),
  (gen_random_uuid(), 'BAO', 'Business Affairs Office', NOW(), NOW()),
  (gen_random_uuid(), 'BAC', 'Bids and Awards Committee Secretariat', NOW(), NOW()),
  (gen_random_uuid(), 'AAP', 'Alumni Affairs and Placement Services', NOW(), NOW())
ON CONFLICT (code) DO NOTHING;
