import type { Document } from "./types"

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "1",
    title: "Research Methodology Guidelines 2024",
    description: "Comprehensive guide for conducting research at LSPU",
    category: "Research",
    tags: ["research", "methodology", "guidelines"],
    uploadedBy: "Dr. Maria Santos",
    uploadedById: "user-1",
    uploadedAt: new Date("2024-01-15"),
    fileUrl: "/documents/research-methodology.pdf",
    fileType: "PDF",
    fileSize: 2500000,
    downloads: 245,
    views: 892,
    version: 2,
  },
  {
    id: "2",
    title: "Data Privacy Act Compliance Manual",
    description: "RA 10173 compliance guidelines for university operations",
    category: "Policy",
    tags: ["privacy", "compliance", "legal"],
    uploadedBy: "Admin User",
    uploadedById: "user-2",
    uploadedAt: new Date("2024-02-01"),
    fileUrl: "/documents/data-privacy.pdf",
    fileType: "PDF",
    fileSize: 1800000,
    downloads: 156,
    views: 543,
    version: 1,
  },
  {
    id: "3",
    title: "Computer Science Curriculum 2024",
    description: "Updated CS curriculum aligned with CHED standards",
    category: "Academic",
    tags: ["curriculum", "computer science", "ched"],
    uploadedBy: "Dr. Maria Santos",
    uploadedById: "user-3",
    uploadedAt: new Date("2024-03-10"),
    fileUrl: "/documents/cs-curriculum.pdf",
    fileType: "PDF",
    fileSize: 3200000,
    downloads: 389,
    views: 1245,
    version: 3,
  },
  {
    id: "4",
    title: "Extension Program Best Practices",
    description: "Community engagement and extension program guidelines",
    category: "Extension",
    tags: ["extension", "community", "outreach"],
    uploadedBy: "External Partner",
    uploadedById: "user-4",
    uploadedAt: new Date("2024-03-20"),
    fileUrl: "/documents/extension-practices.pdf",
    fileType: "PDF",
    fileSize: 2100000,
    downloads: 98,
    views: 321,
    version: 1,
  },
]
