import type { Document, ForumPost, AnalyticsData } from "./types"

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "1",
    title: "Research Methodology Guidelines 2024",
    description: "Comprehensive guide for conducting research at LSPU",
    category: "Research",
    tags: ["research", "methodology", "guidelines"],
    uploadedBy: "Dr. Maria Santos",
    uploadedAt: new Date("2024-01-15"),
    fileUrl: "/documents/research-methodology.pdf",
    fileType: "PDF",
    fileSize: 2500000,
    downloads: 245,
    views: 892,
    version: 2,
  },
  {
    id: "2",
    title: "Data Privacy Act Compliance Manual",
    description: "RA 10173 compliance guidelines for university operations",
    category: "Policy",
    tags: ["privacy", "compliance", "legal"],
    uploadedBy: "Admin User",
    uploadedAt: new Date("2024-02-01"),
    fileUrl: "/documents/data-privacy.pdf",
    fileType: "PDF",
    fileSize: 1800000,
    downloads: 156,
    views: 543,
    version: 1,
  },
  {
    id: "3",
    title: "Computer Science Curriculum 2024",
    description: "Updated CS curriculum aligned with CHED standards",
    category: "Academic",
    tags: ["curriculum", "computer science", "ched"],
    uploadedBy: "Dr. Maria Santos",
    uploadedAt: new Date("2024-03-10"),
    fileUrl: "/documents/cs-curriculum.pdf",
    fileType: "PDF",
    fileSize: 3200000,
    downloads: 389,
    views: 1245,
    version: 3,
  },
  {
    id: "4",
    title: "Extension Program Best Practices",
    description: "Community engagement and extension program guidelines",
    category: "Extension",
    tags: ["extension", "community", "outreach"],
    uploadedBy: "External Partner",
    uploadedAt: new Date("2024-03-20"),
    fileUrl: "/documents/extension-practices.pdf",
    fileType: "PDF",
    fileSize: 2100000,
    downloads: 98,
    views: 321,
    version: 1,
  },
]

export const MOCK_FORUM_POSTS: ForumPost[] = [
  {
    id: "1",
    title: "Best Practices for Online Teaching",
    content:
      "I would like to share some effective strategies for online teaching that I have implemented this semester...",
    author: "Dr. Maria Santos",
    authorRole: "faculty",
    category: "Teaching",
    tags: ["online learning", "pedagogy", "best practices"],
    createdAt: new Date("2024-03-15"),
    replies: [
      {
        id: "1-1",
        content: "Thank you for sharing! The breakout room strategy is very helpful.",
        author: "Juan Dela Cruz",
        authorRole: "student",
        createdAt: new Date("2024-03-16"),
        likes: 5,
      },
    ],
    likes: 23,
    views: 156,
  },
  {
    id: "2",
    title: "Research Collaboration Opportunities",
    content: "Looking for faculty members interested in AI and machine learning research collaboration...",
    author: "External Partner",
    authorRole: "external",
    category: "Research",
    tags: ["collaboration", "ai", "machine learning"],
    createdAt: new Date("2024-03-18"),
    replies: [],
    likes: 12,
    views: 89,
  },
]

export const MOCK_ANALYTICS: AnalyticsData = {
  totalDocuments: 1247,
  totalUsers: 3456,
  totalDownloads: 12890,
  totalViews: 45678,
  recentActivity: [
    {
      id: "1",
      type: "upload",
      user: "Dr. Maria Santos",
      description: 'Uploaded "Research Methodology Guidelines 2024"',
      timestamp: new Date("2024-03-20T10:30:00"),
    },
    {
      id: "2",
      type: "download",
      user: "Juan Dela Cruz",
      description: 'Downloaded "Computer Science Curriculum 2024"',
      timestamp: new Date("2024-03-20T09:15:00"),
    },
    {
      id: "3",
      type: "forum",
      user: "External Partner",
      description: "Posted in Research Collaboration forum",
      timestamp: new Date("2024-03-19T16:45:00"),
    },
  ],
  popularDocuments: MOCK_DOCUMENTS.slice(0, 3),
  categoryDistribution: [
    { category: "Research", count: 345 },
    { category: "Academic", count: 456 },
    { category: "Policy", count: 234 },
    { category: "Extension", count: 212 },
  ],
}
